### ISSUE TITLE
Samsung TV not playing videos any more

### ISSUE THREAD

**Issue by aleho** [gerbera/gerbera#2679]
<details> 
<summary>Compile Info</summary>

```
Gerbera UPnP Server 1.11.0
Copyright 2016-2022 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=NO
WITH_MAGIC=YES
WITH_MYSQL=YES
WITH_CURL=YES
WITH_INOTIFY=YES
WITH_JS=YES
WITH_TAGLIB=YES
WITH_AVCODEC=YES
WITH_FFMPEGTHUMBNAILER=YES
WITH_EXIF=YES
WITH_EXIV2=NO
WITH_MATROSKA=YES
WITH_WAVPACK=YES
WITH_SYSTEMD=NO
WITH_LASTFM=NO
WITH_DEBUG=YES
WITH_TESTS=NO

Git info:
-------------
Git Branch: HEAD
Git Commit: d73d8c1346213d784753c02ea771970500e0df2a
```

</details>

With 1.11.0 / latest in Docker no videos can be played at all.
There are also no thumbnails shown or generated.

Sometimes when starting to play a video, Gerbera just crashes.
[gerbera_1.11.0_tv.log](https://github.com/gerbera/gerbera/files/9104848/gerbera.log)

Using the web UI videos can be played just fine, thumbnails are also generated.

Log file with `docker run -ti --rm --network host --volumes-from gerbera gerbera/gerbera:latest gerbera --port=49494 --config /var/run/gerbera/config.xml --debug`:
[gerbera_1.11.0_web.log](https://github.com/gerbera/gerbera/files/9104850/gerbera.log)

---

With 1.10.0 videos can be played, but after exiting, there's always a crash (apparently trying to set the bookmark).

[gerbera_1.10.0.log](https://github.com/gerbera/gerbera/files/9104893/gerbera1.10.0.log)

**Comment by jfikar** [comment]
The same for LG OLED C9. Gerbera 1.10.0 works, while 1.11.0 does not. For 1.11.0 TV shows no thumbnails and says file format not recognized, when I try to play a file.

Both gerberas use the same pupnp 1.14.12 and I compile it by myself on armhf following:

```
./bootstrap.sh
./configure --prefix=~/upnp --disable-blocking-tcp-connections --enable-reuseaddr
```
and for gerbera:
```
cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_SYSTEMD=0 -DWITH_DEBUG=0 -DSTATIC_LIBUPNP=1 -DWITH_EXIV2=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/upnp/ ..
```

**Comment by KarlStraussberger** [comment]
> <details> 
> <summary>Compile Info</summary>
> 
> ```
> Gerbera UPnP Server 1.11.0
> Copyright 2016-2022 Gerbera Contributors.
> Licence GPLv2: GNU GPL version 2.
> This is free software: you are free to change and redistribute it.
> 
> Compile info
> -------------
> WITH_NPUPNP=NO
> WITH_MAGIC=YES
> WITH_MYSQL=YES
> WITH_CURL=YES
> WITH_INOTIFY=YES
> WITH_JS=YES
> WITH_TAGLIB=YES
> WITH_AVCODEC=YES
> WITH_FFMPEGTHUMBNAILER=YES
> WITH_EXIF=YES
> WITH_EXIV2=NO
> WITH_MATROSKA=YES
> WITH_WAVPACK=YES
> WITH_SYSTEMD=NO
> WITH_LASTFM=NO
> WITH_DEBUG=YES
> WITH_TESTS=NO
> 
> Git info:
> -------------
> Git Branch: HEAD
> Git Commit: d73d8c1346213d784753c02ea771970500e0df2a
> ```
> 
> </details>
> 
> 
> With 1.11.0 / latest in Docker no videos can be played at all.
> There are also no thumbnails shown or generated.
> 
> Sometimes when starting to play a video, Gerbera just crashes.
> [gerbera.log](https://github.com/gerbera/gerbera/files/9104848/gerbera.log)
> 
> 
> Using the web UI videos can be played just fine, thumbnails are also generated.
> 
> 
> Log file with `docker run -ti --rm --network host --volumes-from gerbera gerbera/gerbera:latest gerbera --port=49494 --config /var/run/gerbera/config.xml --debug`:
> [gerbera_1.11.0.log](https://github.com/gerbera/gerbera/files/9104850/gerbera.log)
> 
> 
> ---
> 
> 
> With 1.10.0 videos can be played, but after exiting, there's always a crash (apparently trying to set the bookmark).
> 
> [gerbera_1.10.0.log](https://github.com/gerbera/gerbera/files/9104893/gerbera1.10.0.log)
> 

Seems you've set the `virtualUrl` to `https://gerbera.localhost/`. To me this means you've got a reverse proxy set up. If the certificate is self-signed or the like, your device will refuse to connect. Maybe you can try without virtualUrl.

**Comment by KarlStraussberger** [comment]
> The same for LG OLED C9. Gerbera 1.10.0 works, while 1.11.0 does not. For 1.11.0 TV shows no thumbnails and says file format not recognized, when I try to play a file.
> 
> Both gerberas use the same pupnp 1.14.12 and I compile it by myself on armhf following:
> 
> ```
> ./bootstrap.sh
> ./configure --prefix=~/upnp --disable-blocking-tcp-connections --enable-reuseaddr
> ```
> and for gerbera:
> ```
> cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_SYSTEMD=0 -DWITH_DEBUG=0 -DSTATIC_LIBUPNP=1 -DWITH_EXIV2=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=~/upnp/ ..
> ```
> 

Can you also provide some logs, please? You need to compile `-DWITH_DEBUG=1` and run with `--debug`.

**Comment by aleho** [comment]
> Seems you've set the `virtualUrl` to `https://gerbera.localhost/`. To me this means you've got a reverse proxy set up. If the certificate is self-signed or the like, your device will refuse to connect. Maybe you can try without virtualUrl.

The reverse proxy is just for the UI. The certificate is a valid LetsEncrypt, nothing self-signed.

DLNA is advertised (and can be browsed successfully) via port 49494 and in IP. VLC shows `upnp://http://10.0.0.100:49494/upnp/control/cds&ObjectID=0` and plays videos in any version.

Is this setup wrong?

**Comment by KarlStraussberger** [comment]
The virtualUrl is also used for resources! Are you sure you have a cert for `gerbera.localhost`? Your 1.10 log shows the ip.  So this may be the change that causes your problem.

can you try without virtualurl.

**Comment by aleho** [comment]
> The virtualUrl is also used for resources!
>  Your 1.10 log shows the ip. So this may be the change that causes your problem.

Ah, so a change between 1.10 and 1.11 was virtual URL being used for resources as well?
My basic configuration hasn't changed for quite some time now (excluding new settings that were required).


> Are you sure you have a cert for `gerbera.localhost`?

No, it's not `gerbera.localhost`, I replaced it (sorry for not mentioning that 😁).
The actual URL is a valid public domain.


> can you try without virtualurl.

No change without it. Resources are in `http://IP` format, I just checked UI and VLC.
Gerbera still crashes as soon as a video is selected. No thumbnails either.

**Comment by KarlStraussberger** [comment]
I could not find any trace of a crash in your logs. Either you posted the wrong files or the crash is really hard. Can you run gerbera in `gdb` to get a stacktrace?

**Comment by aleho** [comment]
The first log file is a "crash" where Gerbera just seems to either die or exit.

TV tries to play the file (no bookmarks) and says "format not supported" (or something alike; the error is bogus, the file is supported and plays in <1.11), but playback is never initiated according to logs.
The container then restarts (or the process exits, depending on how I start Gerbera).
This makes the TV UI freeze and wait for the server to come back alive.

I can try to provide a stacktrace with 1.11.0 (I'm guessing there's no point in trying to debug the set-bookmark crash in 1.10).
Do you have a container with debug symbols built in?

**Comment by KarlStraussberger** [comment]
The crash is not a crash but a SIGINT which gerbera got. I cannot see where it comes from. Some security in the container.

The containers are without debug symbol for size :-(

**Comment by aleho** [comment]
Could you maybe provide a container extending the production ones with debug symbols built in?

It's easy for me to just run the process in a container, but setting up a build environment will definitely take quite some time (I'll try to do it anyway, but can't promise when I'll get to it).


For me there are two things I'd like to provide more insight into:

- Why are there no thumbnails on my TV in 1.11?
- Why does the container / process exit after initiating playback on my TV?

Is there anything else you'd need (apart from attaching gdb to a running Gerbera process)?

**Comment by KarlStraussberger** [comment]
I just prepared a Dockerfile that builds a docker image locally.

[Dockerfile.zip](https://github.com/gerbera/gerbera/files/9558620/Dockerfile.zip)

Just copy it to the source root directory and run `docker build -t gerbera-debug . -f Dockerfile.debug`

**Comment by aleho** [comment]
Great, that helped a lot! (Had to add gdb to the packages though, because attaching from outside a container is a bit problematic.)

Segfault happens after TV says "Video not supported" and selecting the "Abort" dialog option:

[backtrace.log](https://github.com/gerbera/gerbera/files/9594056/backtrace.log)
[output.log](https://github.com/gerbera/gerbera/files/9594057/output.log)

---

Regarding the `virtualURL` I have to admit I made a mistake: the change that happened between 1.10.0 and 1.11.0 causes the TV not to show thmubnails or be able to play videos! The setting does influence whether my TV can play videos at all! Sorry for the confusion, I must have forgotten to restart the container after deploying the config file without that setting.

Nevertheless here's the crash without `virtualURL`:

[backtrace_no_virtualURL.log](https://github.com/gerbera/gerbera/files/9594095/backtrace_no_virtualURL.log)


All test run from the latest commit in `master`.

Hope this helps!

**Comment by KarlStraussberger** [comment]
Seems that on abort the TV sends a corrupted setBookmark request. I'll create a PR with stabilised code and them we can look at the remaining issues again.

**Comment by KarlStraussberger** [comment]
See PR #2706

**Comment by KarlStraussberger** [comment]
I tried to reproduce the crash on the XML content by creating a test, but failed. I ask you to add the attached code to your environment which may work differently.
[docker-dbg.zip](https://github.com/gerbera/gerbera/files/9625565/docker-dbg.zip)

If the test `UpnpXmlTest.SamsungBookmark` does not fail we need to add further printouts to the code to find out what's breaking gerbera

**Comment by aleho** [comment]
No, the tests don't fail. I tried changing the XML to something invalid on purpose but the tests still didn't fail (the test was run though).

**Comment by KarlStraussberger** [comment]
Can you try commenting out the following line:

https://github.com/gerbera/gerbera/blob/c4c4e66e52bac37a2ef7a2729a9d69e78ab171db/src/action_request.cc#L77

**Comment by aleho** [comment]
Still crashes in the XML lib. Tests complete as well.

**Comment by KarlStraussberger** [comment]
So it seems that there is more to the request than we can see. That means: Can you try to cut the request with wireshark or tcpdump that we see bad details.

**Comment by aleho** [comment]
According to the wire dump the complete XML, before it has been processed by the receiving layer, looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?><s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><u:X_SetBookmark xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><ObjectID>7</ObjectID><PosSecond>4</PosSecond><CategoryType>0</CategoryType><RID>0</RID></u:X_SetBookmark></s:Body></s:Envelope>
```

I could provide you with the capture file, but I'd rather do that in a chat / via email than in this issue here.

**Comment by KarlStraussberger** [comment]
Just send me an email with the capture attached.

**Comment by aleho** [comment]
I don't want to nag you, but did you receive my email?
Just to make sure it wasn't flagged as spam accidentally.

**Comment by KarlStraussberger** [comment]
Yes, I received it. You forgot to send extra time to understand the issue :smile:

**Comment by aleho** [comment]
Oh my! I'm sorry!

Please, just let me know if there's anything I can do to help.

**Comment by KarlStraussberger** [comment]
I just switched the container to alpine 3.16 and got some messages on the dependency from `ffmpegthumbnailer `to `libav*`.

Maybe you can take a look at the new HEAD (it includes Dockerfile.debug)

**Comment by KarlStraussberger** [comment]
> The `Dockerfile.debug` doesn't build here, the install-googletests script fails.

Good point, forgot that change:
`ldconfig /`

**Comment by KarlStraussberger** [comment]
> Exactly that was my problem. When connecting from a laptop with a browser as https://alpine:49152 it was not working. So I introduced `<virtualURL>alpine:49152</virtualURL>`. That worked fine with the laptop, bud didn't work on the LG TV.
> 
> After removing virtualURL from the config.xml, LG TV works again, but on laptop I have to use https://ip.add.re.ss:49152. Is there a way to have both at the same time?
> 

I recommend setting up a reverse proxy instead of using `virtualUrl`. We may need another option to define the url in the UPNP reponse.

> > Can you also provide some logs, please? You need to compile -DWITH_DEBUG=1 and run with --debug.
> 
> The log files are very big and contain a lot of information I'm not at ease to share. Is there a way to strip e.g. the filenames? I only thought about running a second instance of Gerbera on just a couple of selected files.
> 

You may send the log as mail or upload it to *drive and send me a link.

> But at the same time, Gerbera stopped to compile on my Alpine Edge, so I rolled back to stable Alpine release 3.16. It took some time.
> 
> > I just switched the container to alpine 3.16 and got some messages on the dependency from ffmpegthumbnailer to libav*.
> 
> I saw this one as well. For some reason Alpine seems to mix up ffmpeg and libav. There are packages ffmpeg4-dev-4.4.1-r3 (ffmpeg?) and ffmpeg-dev-5.0.1-r1 (libav?) in 3.16. The ffmpegthumbnailer-dev-2.2.2-r3 seems to work only with the version 4.

I fear that there are more incompatible shared libs in alpine. It's worth a try to make a debug container defintion that uses static libs.

**Comment by KarlStraussberger** [comment]
> No luck here.
> 
> XML parsing still crashes.
> 
> The `Dockerfile.debug` doesn't build here, the install-googletests script fails.

@aleho I fixed the script and migrated the `Dockerfile.debug` to use more self-compiled recent libraries.

**Comment by aleho** [comment]
Thanks!

The `Dockerfile.debug` is missing a copy of libduktape:

```diff
diff --git a/Dockerfile.debug b/Dockerfile.debug
index c633898e..3f260c53 100644
--- a/Dockerfile.debug
+++ b/Dockerfile.debug
@@ -139,6 +139,8 @@ COPY --from=builder /usr/local/lib/libwavpack.so* /usr/lib/
 COPY --from=builder /usr/local/lib/libfmt.so* /usr/lib/
 # Copy spdlog
 COPY --from=builder /usr/local/lib/libspdlog.so* /usr/lib/
+# Copy duktape
+COPY --from=builder /usr/local/lib/libduktape.so* /usr/lib/
 
 # Copy Gerbera
 COPY --from=builder /gerbera_build/build/gerbera /bin/gerbera
```

---

Apart from that the segfault has different details now it seems, but still crashes at XML parsing:

```gdb
#1  0x000056068a970955 in xmlChild (root=..., child=0x56068ace3830 "ObjectID") at /gerbera_build/src/util/upnp_quirks.cc:137
        childNode = {_root = 0x7f1928468ca0}
#2  0x000056068a971c1e in Quirks::saveSamsungBookMarkedPosition (this=0x7f192854e920, database=..., request=...)
    at /gerbera_build/src/util/upnp_quirks.cc:219
        objectID = 675712128
        categoryType = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7f1928468ce0 ""}, _M_string_length = 94586094706832, {_M_local_buf = "\220WY(\001\000\000\000(`6(\031\177\000", 
            _M_allocated_capacity = 4971911056}}
        rID = {static npos = 18446744073709551615, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7f1928468d00 " \215F(\031\177"}, _M_string_length = 94586093609760, {
            _M_local_buf = "\275\217F(\031\177\000\000(`6(\031\177\000", _M_allocated_capacity = 139746026622909}}
        playStatus = {<std::__shared_ptr<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x128468ce0, _M_refcount = {
              _M_pi = 0x7f1928469000}}, <No data fields>}
        bookMarkPos = 32537
        divider = 1
        reqRoot = {_root = 0x7f19285354d8}
        __FUNCTION__ = "saveSamsungBookMarkedPosition"
        response = {_M_t = {<std::__uniq_ptr_impl<pugi::xml_document, std::default_delete<pugi::xml_document> >> = {
              _M_t = {<std::_Tuple_impl<0, pugi::xml_document*, std::default_delete<pugi::xml_document> >> = {<std::_Tuple_impl<1, std::default_delete<pugi::xml_document> >> = {<std::_Head_base<1, std::default_delete<pugi::xml_document>, true>> = {
                      _M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, pugi::xml_document*, false>> = {
                    _M_head_impl = 0x128468ce0}, <No data fields>}, <No data fields>}}, <No data fields>}}
#3  0x000056068a932390 in ContentDirectoryService::doSamsungBookmark (this=0x7f1928366010, request=...) at /gerbera_build/src/upnp_cds.cc:311
        __FUNCTION__ = "doSamsungBookmark"
#4  0x000056068a932aee in ContentDirectoryService::processActionRequest (this=0x7f1928366010, request=...)
    at /gerbera_build/src/upnp_cds.cc:358
        __FUNCTION__ = "processActionRequest"
#5  0x000056068a91d9ae in Server::routeActionRequest (this=0x7f1928e32500, request=...) at /gerbera_build/src/server.cc:468
        __FUNCTION__ = "routeActionRequest"
#6  0x000056068a91cfc5 in Server::handleUpnpRootDeviceEvent (this=0x7f1928e32500, eventType=UPNP_CONTROL_ACTION_REQUEST, 
    event=0x7f1928472c50) at /gerbera_build/src/server.cc:391
        request = {upnp_request = 0x7f1928472c50, errCode = 0, actionName = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f1928468fb0 "X_SetBookmark"}, _M_string_length = 13, {_M_local_buf = "X_SetBookmark\000\000", 
              _M_allocated_capacity = 8029709728308485976}}, UDN = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f1928550cb0 "uuid:3841e68c-1c63-49af-b93e-35a9f9dfbf5b"}, _M_string_length = 41, {
              _M_local_buf = ")", '\000' <repeats 14 times>, _M_allocated_capacity = 41}}, serviceID = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f1928550ce0 "urn:upnp-org:serviceId:ContentDirectory"}, _M_string_length = 39, {
              _M_local_buf = "'\000\000\000\000\000\000\000\320\031\224.\031\177\000", _M_allocated_capacity = 39}}, quirks = {
            _M_t = {<std::__uniq_ptr_impl<Quirks, std::default_delete<Quirks> >> = {
                _M_t = {<std::_Tuple_impl<0, Quirks*, std::default_delete<Quirks> >> = {<std::_Tuple_impl<1, std::default_delete<Quirks> >> = {<std::_Head_base<1, std::default_delete<Quirks>, true>> = {
                        _M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, Quirks*, false>> = {
                      _M_head_impl = 0x7f192854e920}, <No data fields>}, <No data fields>}}, <No data fields>}}, response = {
            _M_t = {<std::__uniq_ptr_impl<pugi::xml_document, std::default_delete<pugi::xml_document> >> = {
                _M_t = {<std::_Tuple_impl<0, pugi::xml_document*, std::default_delete<pugi::xml_document> >> = {<std::_Tuple_impl<1, std::default_delete<pugi::xml_document> >> = {<std::_Head_base<1, std::default_delete<pugi::xml_document>, true>> = {
                        _M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, pugi::xml_document*, false>> = {
                      _M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, <No data fields>}}}
        ret = 0
        __FUNCTION__ = "handleUpnpRootDeviceEvent"
#7  0x000056068a91955a in operator()<Upnp_EventType_e, void const*, void*> (__closure=0x0, eventType=UPNP_CONTROL_ACTION_REQUEST, 
    event=0x7f1928472c50, cookie=0x7f1928e32500) at /gerbera_build/src/server.cc:172
No locals.
#8  0x000056068a91fd1d in _FUN<Upnp_EventType_e, void const*, void*> () at /gerbera_build/src/server.cc:172
No locals.
#9  0x00007f192e947ad9 in handle_invoke_action (req_node=0x7f192846ab90, soap_info=0x7f192854eaf0, request=0x7f19284692f8, 
    info=0x7f1928469270) at ../../upnp/src/soap/soap_device.c:436
        actionRequestDoc = 0x7f192853e290
        err_str = <optimized out>
        act_node = 0x7f192856beb0 "<u:X_SetBookmark xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">\r\n<ObjectID>7</ObjectID>\r\n<PosSecond>2</PosSecond>\r\n<CategoryType>0</CategoryType>\r\n<RID>0</RID>\r\n</u:X_SetBookmark>\r\n"
        hdr_value = {buf = 0x7f192854ff00 "SEC_HHP_[TV]WZ/1.0 DLNADOC/1.50", length = 31}
        save_char = 34 '"'
        action = 0x7f1928472c50
        actionResultDoc = 0x0
        err_code = <optimized out>
        action_name = {buf = 0x7f19282e9081 "X_SetBookmark", length = <optimized out>}
        save_char = <optimized out>
        action = <optimized out>
        actionRequestDoc = <optimized out>
        actionResultDoc = <optimized out>
        err_code = <optimized out>
        err_str = <optimized out>
        action_name = <optimized out>
        act_node = <optimized out>
        hdr_value = <optimized out>
        error_handler = <optimized out>
#10 soap_device_callback (parser=<optimized out>, request=0x7f19284692f8, info=0x7f1928469270) at ../../upnp/src/soap/soap_device.c:809
        err_code = <optimized out>
        xml_doc = 0x7f192846ae10
        soap_info = 0x7f192854eaf0
        req_node = <optimized out>
#11 0x00007f192e948d50 in dispatch_request (hparser=0x7f19284692f8, info=0x7f1928469270) at ../../upnp/src/genlib/miniserver/miniserver.c:348
        min_size = <optimized out>
        request = 0x7f19284692f8
        cookie = <optimized out>
        header = {buf = 0x7f19285505b0 "10.0.0.100:49494", length = 16}
        callback = 0x7f192e9472b3 <soap_device_callback>
        host_validate_callback = <optimized out>
        rc = 0
        host_port = "10.0.0.100\000\064\071\064\071\064", '\000' <repeats 239 times>
        header = <optimized out>
        min_size = <optimized out>
        request = <optimized out>
        callback = <optimized out>
        host_validate_callback = <optimized out>
        cookie = <optimized out>
        rc = <optimized out>
        host_port = <optimized out>
        ExitFunction = <optimized out>
        redir_buf = <optimized out>
        redir_fmt = <optimized out>
        redir_str = <optimized out>
        timeout = <optimized out>
#12 handle_request (args=0x7f1928366910) at ../../upnp/src/genlib/miniserver/miniserver.c:430
        info = {socket = 19, foreign_sockaddr = {ss_family = 2, __ss_padding = "\322\343\n\000\000<", '\000' <repeats 111 times>, __ss_align = 0}}
        http_error_code = 500
        ret_code = <optimized out>
        major = 1
        minor = 1
        parser = {msg = {initialized = 1, method = SOAPMETHOD_POST, uri = {type = RELATIVE, scheme = {buff = 0x0, size = 0}, path_type = ABS_PATH, pathquery = {buff = 0x7f19285503f0 "/upnp/control/cds", size = 17}, fragment = {buff = 0x0, size = 0}, hostport = {text = {buff = 0x0, size = 0}, IPaddress = {ss_family = 0, __ss_padding = '\000' <repeats 117 times>, __ss_align = 0}}}, request_method = HTTPMETHOD_PUT, status_code = 0, status_msg = {buf = 0x0, length = 0, capacity = 0, size_inc = 5}, amount_discarded = 0, is_request = 1, major_version = 1, minor_version = 1, headers = {head = {prev = 0x0, next = 0x7f1928550490, item = 0x0}, tail = {prev = 0x7f19285517c0, next = 0x0, item = 0x0}, size = 7, freeNodeList = {head = 0x0, element_size = 24, maxFreeListLength = 100, freeListLength = 0}, free_func = 0x7f192e94b525 <httpheader_free>, cmp_func = 0x7f192e94b518 <httpmsg_compare>}, entity = {buf = 0x7f1928340904 "<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Body><u:X_SetBookmark xmlns:u=\"urn:"..., length = 373}, msg = {buf = 0x7f19283407f0 "POST /upnp/control/cds HTTP/1.1\r\nAccept: */*\r\nUser-Agent: SEC_HHP_[TV]WZ/1.0 DLNADOC/1.50\r\nHost: 10.0.0.100:49494\r\nSOAPACTION: \"urn:schemas-upnp-org:service:ContentDirectory:1#X_SetBookmark\"\r\nCONTENT-"..., length = 649, capacity = 649, size_inc = 5}, urlbuf = 0x7f19285503f0 "/upnp/control/cds"}, http_error_code = 400, valid_ssdp_notify_hack = 0, position = POS_COMPLETE, ent_position = 2, content_length = 373, chunk_size = 0, entity_start_position = 276, scanner = {msg = 0x7f1928469480, cursor = 276, entire_msg_loaded = 0}}
        hmsg = 0x7f19284692f8
        timeout = 30
        request = 0x7f1928366910
        connfd = <optimized out>
#13 0x00007f192e94206a in WorkerThread (arg=0x7f192e96a1c0 <gMiniServerThreadPool>) at ../../upnp/src/threadutil/ThreadPool.c:591
        start = 1666355032
        job = 0x7f1928564bd0
        head = <optimized out>
        timeout = {tv_sec = 0, tv_nsec = 0}
        retCode = <optimized out>
        persistent = 0
        tp = 0x7f192e96a1c0 <gMiniServerThreadPool>
#14 0x00007f192e9c81f5 in ?? () from /lib/ld-musl-x86_64.so.1
```

Are the dumped variable/value pairs supposed to be address pointers or actual values? (Sorry, the last time I did serious C development was about 15 years ago).

Because if they're supposed to be actual values,

```
objectID = 675712128
bookMarkPos = 32537
```

seems to be totally off (should be 7 and 2).
Are these overflows and caused by broken parsing?

**Comment by KarlStraussberger** [comment]
> Thanks!
> 
> The `Dockerfile.debug` is missing a copy of libduktape:
> 

Thanks for the hint. I'll incorporate that in the next PR

> Are the dumped variable/value pairs supposed to be address pointers or actual values? (Sorry, the last time I did serious C development was about 15 years ago).
> 

I'm not serious about this, it's just playing around 😸 

> Because if they're supposed to be actual values,
> 
> ```
> objectID = 675712128
> bookMarkPos = 32537
> ```
> 
> seems to be totally off (should be 7 and 2). Are these overflows and caused by broken parsing?

The values don't get initialised because the crash happens before.

The only thing we learned from the changes is, that the alpine libraries do not influence the issue. Seems the request gets corrupted on its way into the container.

**Comment by KarlStraussberger** [comment]
I produced another set of changes #2729 that assume that there is an broken reference to some object.

**Comment by aleho** [comment]
Look identical to me:

```gdb
#0  0x000055dad5d57647 in pugi::xml_node::child(char const*) const ()
No symbol table info available.
#1  0x000055dad5aafa19 in xmlChild (root=..., child=0x55dad5e22830 "ObjectID") at /gerbera_build/src/util/upnp_quirks.cc:137
        childNode = {_root = 0x7f394bfbbca0}
#2  0x000055dad5ab0cf2 in Quirks::saveSamsungBookMarkedPosition (this=0x7f394c0a49c0, database=..., request=...) at /gerbera_build/src/util/upnp_quirks.cc:219
        objectID = 1274788992
        categoryType = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7f394bfbbce0 ""}, _M_string_length = 94398375743692, {_M_local_buf = "\020\214\016L\001\000\000\000(\220\nL9\177\000", _M_allocated_capacity = 5570989072}}
        rID = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
            _M_p = 0x7f394bfbbd00 " \275\373K9\177"}, _M_string_length = 94398374646560, {_M_local_buf = "\275\277\373K9\177\000\000(\220\nL9\177\000", 
            _M_allocated_capacity = 139884064653245}}
        playStatus = {<std::__shared_ptr<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x14bfbbce0, _M_refcount = {_M_pi = 0x7f394bfbc000}}, <No data fields>}
        bookMarkPos = 32569
        divider = 1
        reqRoot = {_root = 0x7f394c0666c8}
        __FUNCTION__ = "saveSamsungBookMarkedPosition"
        response = {_M_t = {<std::__uniq_ptr_impl<pugi::xml_document, std::default_delete<pugi::xml_document> >> = {
              _M_t = {<std::_Tuple_impl<0, pugi::xml_document*, std::default_delete<pugi::xml_document> >> = {<std::_Tuple_impl<1, std::default_delete<pugi::xml_document> >> = {<std::_Head_base<1, std::default_delete<pugi::xml_document>, true>> = {_M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, pugi::xml_document*, false>> = {
                    _M_head_impl = 0x14bfbbce0}, <No data fields>}, <No data fields>}}, <No data fields>}}
#3  0x000055dad5a713cc in ContentDirectoryService::doSamsungBookmark (this=0x7f394c0a9010, request=...) at /gerbera_build/src/upnp_cds.cc:311
        __FUNCTION__ = "doSamsungBookmark"
#4  0x000055dad5a71b2a in ContentDirectoryService::processActionRequest (this=0x7f394c0a9010, request=...) at /gerbera_build/src/upnp_cds.cc:358
        __FUNCTION__ = "processActionRequest"
#5  0x000055dad5a5ca06 in Server::routeActionRequest (this=0x7f394c985500, request=...) at /gerbera_build/src/server.cc:468
        __FUNCTION__ = "routeActionRequest"
#6  0x000055dad5a5c01e in Server::handleUpnpRootDeviceEvent (this=0x7f394c985500, eventType=UPNP_CONTROL_ACTION_REQUEST, event=0x7f394bee12e0) at /gerbera_build/src/server.cc:391
        request = {upnp_request = 0x7f394bee12e0, errCode = 0, actionName = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f394bfbbfb0 "X_SetBookmark"}, 
            _M_string_length = 13, {_M_local_buf = "X_SetBookmark\000\000", _M_allocated_capacity = 8029709728308485976}}, UDN = {static npos = 18446744073709551615, 
            _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f394c0a1610 "uuid:3841e68c-1c63-49af-b93e-35a9f9dfbf5b"}, _M_string_length = 41, {_M_local_buf = ")", '\000' <repeats 14 times>, _M_allocated_capacity = 41}}, 
          serviceID = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
              _M_p = 0x7f394c0a1640 "urn:upnp-org:serviceId:ContentDirectory"}, _M_string_length = 39, {_M_local_buf = "'\000\000\000\000\000\000\000\320IIR9\177\000", 
              _M_allocated_capacity = 39}}, quirks = {_M_t = {<std::__uniq_ptr_impl<Quirks, std::default_delete<Quirks> >> = {
                _M_t = {<std::_Tuple_impl<0, Quirks*, std::default_delete<Quirks> >> = {<std::_Tuple_impl<1, std::default_delete<Quirks> >> = {<std::_Head_base<1, std::default_delete<Quirks>, true>> = {_M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, Quirks*, false>> = {
                      _M_head_impl = 0x7f394c0a49c0}, <No data fields>}, <No data fields>}}, <No data fields>}}, response = {
            _M_t = {<std::__uniq_ptr_impl<pugi::xml_document, std::default_delete<pugi::xml_document> >> = {
                _M_t = {<std::_Tuple_impl<0, pugi::xml_document*, std::default_delete<pugi::xml_document> >> = {<std::_Tuple_impl<1, std::default_delete<pugi::xml_document> >> = {<std::_Head_base<1, std::default_delete<pugi::xml_document>, true>> = {_M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, pugi::xml_document*, false>> = {
                      _M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, <No data fields>}}}
        ret = 0
        __FUNCTION__ = "handleUpnpRootDeviceEvent"
#7  0x000055dad5a585c8 in operator()<Upnp_EventType_e, void const*, void*> (__closure=0x0, eventType=UPNP_CONTROL_ACTION_REQUEST, event=0x7f394bee12e0, cookie=0x7f394c985500)
    at /gerbera_build/src/server.cc:172
No locals.
#8  0x000055dad5a5ed75 in _FUN<Upnp_EventType_e, void const*, void*> () at /gerbera_build/src/server.cc:172
No locals.
#9  0x00007f395249aad9 in handle_invoke_action (req_node=0x7f394c0aab90, soap_info=0x7f394c0a3a70, request=0x7f394bfbc2f8, info=0x7f394bfbc270) at ../../upnp/src/soap/soap_device.c:436
        actionRequestDoc = 0x7f394c06f290
        err_str = <optimized out>
        act_node = 0x7f394bee14e0 "<u:X_SetBookmark xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">\r\n<ObjectID>7</ObjectID>\r\n<PosSecond>7</PosSecond>\r\n<CategoryType>0</CategoryType>\r\n<RID>0</RID>\r\n</u:X_SetBookmark>\r\n"
        hdr_value = {buf = 0x7f394c0a0f80 "SEC_HHP_[TV]WZ/1.0 DLNADOC/1.50", length = 31}
        save_char = 34 '"'
        action = 0x7f394bee12e0
        actionResultDoc = 0x0
        err_code = <optimized out>
        action_name = {buf = 0x7f394c0c1f11 "X_SetBookmark", length = <optimized out>}
        save_char = <optimized out>
        action = <optimized out>
        actionRequestDoc = <optimized out>
        actionResultDoc = <optimized out>
        err_code = <optimized out>
        err_str = <optimized out>
        action_name = <optimized out>
        act_node = <optimized out>
        hdr_value = <optimized out>
        error_handler = <optimized out>
```

**Comment by KarlStraussberger** [comment]
You may try the following update of `getRequest` in `action_request.cc` to get more output on `--debug`

```
std::unique_ptr<pugi::xml_document> ActionRequest::getRequest() const
{
    auto request = std::make_unique<pugi::xml_document>();
#if defined(USING_NPUPNP)
    auto ret = request->load_string(upnp_request->xmlAction.c_str());
#else
    DOMString cxml = ixmlPrintDocument(UpnpActionRequest_get_ActionRequest(upnp_request));
    log_debug("strlen(cxml) = {}, cxml = {}", strlen(cxml), cxml);
    auto ret = request->load_string(cxml);
    log_debug("result = {}", ret.description());
    ixmlFreeDOMString(cxml);
#endif

    if (ret.status != pugi::xml_parse_status::status_ok)
        throw_std_runtime_error("Unable to parse ixml: {}", ret.description());
    log_debug("request = {}", UpnpXMLBuilder::printXml(request->document_element()));

    return request;
}
```

**Comment by aleho** [comment]
Sorry, took some time to finish other stuff in my spare time.

I was able to send a request using UPnP Tool with the same device flags enabled.

Requests sent by the Android app crash as well: 
```gdb
#1  0x000055bc93a99a04 in xmlChild (root=..., child=0x55bc93e0d810 "ObjectID") at /gerbera_build/src/util/upnp_quirks.cc:137
        childNode = {_root = 0x7f015bce4ca0}
#2  0x000055bc93a9acdc in Quirks::saveSamsungBookMarkedPosition (this=0x7f015bbe58c0, database=..., request=...) at /gerbera_build/src/util/upnp_quirks.cc:219
        objectID = 1540246656
        categoryType = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f015bce4ce0 ""}, 
          _M_string_length = 94268419338418, {_M_local_buf = "5\001\000\000\001\177\000\000\000P\316[\001\177\000", _M_allocated_capacity = 139642271695157}}
        rID = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f015bce4d00 " M\316[\001\177"}, 
          _M_string_length = 94268419336166, {_M_local_buf = "\275O\316[\001\177\000\000\000P\316[\001\177\000", _M_allocated_capacity = 139643811942333}}
        playStatus = {<std::__shared_ptr<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ClientStatusDetail, (__gnu_cxx::_Lock_policy)2, false, false>> = {<No data fields>}, 
            _M_ptr = 0x7f015c752848, _M_refcount = {_M_pi = 0x7f015bce5000}}, <No data fields>}
        bookMarkPos = 32513
        divider = 1
        reqRoot = {_root = 0x7f015be48e58}
        __FUNCTION__ = "saveSamsungBookMarkedPosition"
        response = {_M_t = {<std::__uniq_ptr_impl<pugi::xml_document, std::default_delete<pugi::xml_document> >> = {
              _M_t = {<std::_Tuple_impl<0, pugi::xml_document*, std::default_delete<pugi::xml_document> >> = {<std::_Tuple_impl<1, std::default_delete<pugi::xml_document> >> = {<std::_Head_base<1, std::default_delete<pugi::xml_document>, true>> = {_M_head_impl = {<No data fields>}}, <No data fields>}, <std::_Head_base<0, pugi::xml_document*, false>> = {
                    _M_head_impl = 0x7f015c752848}, <No data fields>}, <No data fields>}}, <No data fields>}}
```


The XML sent by the TV in comparison to the app also looks identical, apart from tag order:
```
<u:X_SetBookmark xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">\r\n<ObjectID>7</ObjectID>\r\n<PosSecond>4</PosSecond>\r\n<CategoryType>0</CategoryType>\r\n<RID>0</RID>\r\n</u:X_SetBookmark>\r\n
```

```
<u:X_SetBookmark xmlns:u=\"urn:schemas-upnp-org:service:ContentDirectory:1\">\r\n<CategoryType>0</CategoryType>\r\n<RID>0</RID>\r\n<PosSecond>4</PosSecond>\r\n<ObjectID>7</ObjectID>\r\n</u:X_SetBookmark>\r\n
```

Here's the debug output right before the crash:

```
2022-11-12 10:20:08.448  debug: [upnp_clients.cc:222] getInfo(): client info: 10.0.0.22:40862 'Android/31 UPnP/1.1 UPnPTool/1.6.0' -> 'Manual Setup for UserAgent UPnPTool' as None
2022-11-12 10:20:08.448  debug: [server.cc:451] routeActionRequest(): start
2022-11-12 10:20:08.448  debug: [upnp_cds.cc:345] processActionRequest(): start
2022-11-12 10:20:08.448  debug: [upnp_cds.cc:309] doSamsungBookmark(): start
2022-11-12 10:20:08.448  debug: [action_request.cc:76] getRequest(): strlen(cxml) = 216, cxml = <?xml version="1.0"?>
<u:X_SetBookmark xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
<CategoryType>0</CategoryType>
<RID>0</RID>
<PosSecond>4</PosSecond>
<ObjectID>7</ObjectID>
</u:X_SetBookmark>

2022-11-12 10:20:08.448  debug: [action_request.cc:78] getRequest(): result = No error
2022-11-12 10:20:08.448  debug: [action_request.cc:84] getRequest(): request = <u:X_SetBookmark xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
	<CategoryType>0</CategoryType>
	<RID>0</RID>
	<PosSecond>4</PosSecond>
	<ObjectID>7</ObjectID>
</u:X_SetBookmark>


Thread 15 "gerbera" received signal SIGSEGV, Segmentation fault.
```


I guess it's safe to assume now that the XML is clean and the TV is sending a valid string, right?
So maybe there's something wrong with the environment? I'm at the end of my wits here, I have to admit.


It's just a simple and basic Debian host with Docker. You should be able to reproduce it by running Docker inside of an official Debian image:

`docker run -ti --rm --network host --volumes-from gerbera --name gerbera-test gerbera-test gdb --args gerbera --debug --port=49494 --config /var/run/gerbera/config.xml`

**Comment by KarlStraussberger** [comment]
I don't have a clue either, so let's check the environment: What's your docker version

`docker --version` and `dockerd --version`.

**Comment by aleho** [comment]
`Docker version 20.10.19+dfsg1, build d85ef84` and
`containerd github.com/containerd/containerd 1.6.9~ds1 1.6.9~ds1-1`.

I updated before the recent tests.

Before it was `20.10.5` and `1.4.13`.

**Comment by KarlStraussberger** [comment]
No real difference here also

Let's try your architecture `uname -i -m -p`

**Comment by aleho** [comment]
Just a fairly standard Debian installation (setup with Ansible, so not even any custom changes I can't remember :grin:).

If you don't use Debian you should be able to reproduce everything in a Debian stable docker container running the Gerbera container. If you can't reproduce it there's something happening here I cannot debug right now because I really don't know where to start. RAM is 16GB and no limits for the container.

---

`uname -a`

`Linux nas 5.19.0-0.deb11.2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.19.11-1~bpo11+1 (2022-10-03) x86_64 GNU/Linux`

**Comment by jfikar** [comment]
> I recommend setting up a reverse proxy instead of using `virtualUrl`. We may need another option to define the url in the UPNP reponse.

Thanks, it worked at least for a while, then it stopped. I have to see why. Nginx does not have sub in Alpine though.
 
> You may send the log as mail or upload it to *drive and send me a link.

Now everything works with my LG TV.

Moreover, I've even recently upgraded to stable Alpine 3.17 and surprisingly the build-in gerbera-1.12.0-r0 now works fine with my LG TV! It was not the case in Alpine 3.16 and before.

**Comment by KarlStraussberger** [comment]
@aleho I bumped to alpine 3.17. Can you try that out, please?

**Comment by aleho** [comment]
@KarlStraussberger Nothing different so far. Still crashing at XML parsing.

**Comment by KarlStraussberger** [comment]
Did your test already include #2758? No real connection but you never know...

**Comment by aleho** [comment]
No, didn't include that commit, but no change here (tested on TV and with the Android app).

**Comment by KarlStraussberger** [comment]
Obviously there were issues in serveContent and getInfo. It's close to your issue, maybe it's fixed by those changes. So, welcome to the next round of testing.

**Comment by aleho** [comment]
Sorry, I just now realized I never answered.

Tried with the latest master today and UPNP Tool, still a segfault in pugi and ObjectID.

This might be a long shot, but is there an alternative to that lib that we could try there to make sure it's not breaking there?

Were you able to reproduce the problem in a local Docker container at all?

**Comment by KarlStraussberger** [comment]
I cannot reproduce any issue at all. It may be some broken c-library on your system. I've got no clue.

**Comment by whyman** [comment]
Just had a quick glance, maybe the "samsung" methods need the nullptr checks for pClientInfo too?

**Comment by KarlStraussberger** [comment]
Good point. Cleaned up that code in #2796

**Comment by aleho** [comment]
It's strange that you cannot reproduce the segfault.

I tried on 3 systems now: A Fedora and another Debian host with a Gerbera container and Docker-in-Docker setup. All fail.

Here's a small reproducer with a Docker daemon through dind, running a Gerbera container in the isolated daemon:
https://github.com/aleho/gerbera-dind-test

Does this segfault for you if you run X_SetBookmark with UPnPTool?

**Comment by whyman** [comment]
So, I could reproduce the crash in docker with your test repo, and let me just say, amazing work there! Very much appreciated.

The strange thing is, if I copy the config into my local dev environment, blow away my db, and fire off UPnPTool, it all works fine, no crash, very strange.

**Comment by whyman** [comment]
2nd strange thing, if I run 
```
docker run \
    -it --rm \
    --network host \
    --volume /gerbera:/var/run/gerbera \
    --volume /content:/content \
    gerbera/gerbera:$TAG \
    gerbera --port=49494 --config /var/run/gerbera/config.xml --debug```
    
 So just directly on my local docker, its also fine.... odd indeed.

**Comment by aleho** [comment]
Can confirm, works now for me.

Thank you very much for your patience and hard work!
