### ISSUE TITLE
Gerbera 2.0 error: Failed to read /home/user/.mpdascache: No such file or directory

### ISSUE THREAD

**Issue by efermi** [gerbera/gerbera#3002]
After upgrade to 2.0 the following error occurs multiple times per second: `error: Failed to read /home/<user>/.mpdascache: No such file or directory`. I do have a user owned mpdas service running, but why is gerbera is trying to interact with it at all?

OS: Manjaro
/etc/gerbera/config.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">
  <!--
     See https://gerbera.io or read the docs for more
     information on creating and using config.xml configuration files.
    -->
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="no" session-timeout="30">
        <account user="gerbera" password="gerbera" />
      </accounts>
    </ui>
    <name>Gerbera-machine</name>
    <udn>uuid:f407cbbe-53c9-473b-8f1c-5dbe0bc7a996</udn>
    <home>/etc/gerbera</home>
    <webroot>/usr/share/gerbera/web</webroot>
    <!--
        How frequently (in seconds) to send ssdp:alive advertisements.
        Minimum alive value accepted is: 62

        The advertisement will be sent every (A/2)-30 seconds,
        and will have a cache-control max-age of A where A is
        the value configured here. Ex: A value of 62 will result
        in an SSDP advertisement being sent every second.
    -->
    <alive>180</alive>
    <storage>
      <sqlite3 enabled="yes">
        <database-file>gerbera.db</database-file>
      </sqlite3>
    </storage>
    <containers enabled="yes">
      <container location="/LastAdded" title="Recently Added" sort="-last_updated">
        <filter>upnp:class derivedfrom "object.item" and last_updated &gt; "@last7"</filter>
      </container>
      <container location="/LastModified" title="Recently Modified" sort="-last_modified">
        <filter>upnp:class derivedfrom "object.item" and last_modified &gt; "@last7"</filter>
      </container>
    </containers>
    <extended-runtime-options>
      <ffmpegthumbnailer enabled="yes">
        <thumbnail-size>160</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>no</filmstrip-overlay>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
      <mark-played-items enabled="no" suppress-cds-updates="yes">
        <string mode="prepend">*</string>
        <mark>
          <content>video</content>
        </mark>
      </mark-played-items>
    </extended-runtime-options>
  </server>

  <import hidden-files="no">
    <scripting script-charset="UTF-8">
      <common-script>/usr/share/gerbera/js/common.js</common-script>
      <playlist-script>/usr/share/gerbera/js/playlists.js</playlist-script>
      <metafile-script>/usr/share/gerbera/js/metadata.js</metafile-script>
      <virtual-layout type="builtin">
        <import-script>/usr/share/gerbera/js/import.js</import-script>
      </virtual-layout>
    </scripting>
    <mappings>
      <extension-mimetype ignore-unknown="no">
        <map from="asf" to="video/x-ms-asf" />
        <map from="asx" to="video/x-ms-asx" />
        <map from="dff" to="audio/x-dff" />
        <map from="dsd" to="audio/x-dsd" />
        <map from="dsf" to="audio/x-dsf" />
        <map from="flv" to="video/x-flv" />
        <map from="m2ts" to="video/mp2t" />
        <map from="m3u" to="audio/x-mpegurl" />
        <map from="m3u8" to="audio/x-mpegurl" />
        <map from="m4a" to="audio/mp4" />
        <map from="mka" to="audio/x-matroska" />
        <map from="mkv" to="video/x-matroska" />
        <map from="mp3" to="audio/mpeg" />
        <map from="mts" to="video/mp2t" />
        <map from="oga" to="audio/ogg" />
        <map from="ogg" to="audio/ogg" />
        <map from="ogm" to="video/ogg" />
        <map from="ogv" to="video/ogg" />
        <map from="ogx" to="application/ogg" />
        <map from="pls" to="audio/x-scpls" />
        <map from="ts" to="video/mp2t" />
        <map from="tsa" to="audio/mp2t" />
        <map from="tsv" to="video/mp2t" />
        <map from="wax" to="audio/x-ms-wax" />
        <map from="wm" to="video/x-ms-wm" />
        <map from="wma" to="audio/x-ms-wma" />
        <map from="wmv" to="video/x-ms-wmv" />
        <map from="wmx" to="video/x-ms-wmx" />
        <map from="wv" to="audio/x-wavpack" />
        <map from="wvx" to="video/x-ms-wvx" />
        <!-- Uncomment the line below for PS3 divx support -->
        <!-- <map from="avi" to="video/divx" /> -->
        <!-- Uncomment the line below for D-Link DSM / ZyXEL DMA-1000 -->
        <!-- <map from="avi" to="video/avi" /> -->
      </extension-mimetype>
      <mimetype-upnpclass>
        <map from="application/ogg" to="object.item.audioItem.musicTrack" />
        <map from="audio/*" to="object.item.audioItem.musicTrack" />
        <map from="image/*" to="object.item.imageItem" />
        <map from="video/*" to="object.item.videoItem" />
      </mimetype-upnpclass>
      <mimetype-contenttype>
        <treat mimetype="application/ogg" as="ogg" />
        <treat mimetype="audio/L16" as="pcm" />
        <treat mimetype="audio/flac" as="flac" />
        <treat mimetype="audio/mp4" as="mp4" />
        <treat mimetype="audio/mpeg" as="mp3" />
        <treat mimetype="audio/ogg" as="ogg" />
        <treat mimetype="audio/x-dsd" as="dsd" />
        <treat mimetype="audio/x-flac" as="flac" />
        <treat mimetype="audio/x-matroska" as="mka" />
        <treat mimetype="audio/x-mpegurl" as="playlist" />
        <treat mimetype="audio/x-ms-wma" as="wma" />
        <treat mimetype="audio/x-scpls" as="playlist" />
        <treat mimetype="audio/x-wav" as="pcm" />
        <treat mimetype="audio/x-wavpack" as="wv" />
        <treat mimetype="image/jpeg" as="jpg" />
        <treat mimetype="image/png" as="png" />
        <treat mimetype="video/mkv" as="mkv" />
        <treat mimetype="video/mp4" as="mp4" />
        <treat mimetype="video/mpeg" as="mpeg" />
        <treat mimetype="video/x-matroska" as="mkv" />
        <treat mimetype="video/x-mkv" as="mkv" />
        <treat mimetype="video/x-ms-asf" as="asf" />
        <treat mimetype="video/x-ms-asx" as="playlist" />
        <treat mimetype="video/x-msvideo" as="avi" />
      </mimetype-contenttype>
      <mimetype-dlnatransfermode>
        <map from="application/ogg" to="Streaming" />
        <map from="application/x-srt" to="Background" />
        <map from="audio/*" to="Streaming" />
        <map from="image/*" to="Interactive" />
        <map from="srt" to="Background" />
        <map from="text/*" to="Background" />
        <map from="video/*" to="Streaming" />
      </mimetype-dlnatransfermode>
      <contenttype-dlnaprofile>
        <map from="asf" to="VC_ASF_AP_L2_WMA" />
        <map from="avi" to="AVI" />
        <map from="dsd" to="DSF" />
        <map from="flac" to="FLAC" />
        <map from="jpg" to="JPEG_LRG" />
        <map from="mka" to="MKV" />
        <map from="mkv" to="MKV" />
        <map from="mp3" to="MP3" />
        <map from="mp4" to="AVC_MP4_EU" />
        <map from="mpeg" to="MPEG_PS_PAL" />
        <map from="ogg" to="OGG" />
        <map from="pcm" to="LPCM" />
        <map from="png" to="PNG_LRG" />
        <map from="wma" to="WMAFULL" />
      </contenttype-dlnaprofile>
    </mappings>
    <online-content>
      <AppleTrailers enabled="no" refresh="43200" update-at-start="no" resolution="640" />
    </online-content>

    <autoscan use-inotify="yes">
      <directory location="/mnt/wd2/video" mode="inotify" recursive="yes"/>
      <directory location="/home/<user>/videos" mode="inotify" recursive="yes"/>
    </autoscan>

    <resources case-sensitive="no">
      <subtitle>
        <add-file name="%filename%*.srt"/>
        <add-dir name="." ext="srt"/>
        <add-dir name="./Subs" ext="srt"/>
        <add-dir name="./Subs/%filename%" ext="srt"/>
      </subtitle>
    </resources>
  </import>

  <transcoding enabled="no">
    <mimetype-profile-mappings>
      <transcode mimetype="application/ogg" using="vlcmpeg" />
      <transcode mimetype="audio/ogg" using="ogg2mp3" />
      <transcode mimetype="video/x-flv" using="vlcmpeg" />
    </mimetype-profile-mappings>
    <profiles>
      <profile name="ogg2mp3" enabled="no" type="external">
        <mimetype>audio/mpeg</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <agent command="ffmpeg" arguments="-y -i %in -f mp3 %out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>
      <profile name="vlcmpeg" enabled="no" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit" />
        <buffer size="14400000" chunk-size="512000" fill-size="120000" />
      </profile>
    </profiles>
  </transcoding>
</config>


```

**Comment by KarlStraussberger** [comment]
To me this looks like a broken link. You may also try to get rid of the message with `hidden-files="no"` for the directory.

**Comment by efermi** [comment]
1. I've added `hidden-files="no"` to the directory entries
2. found no related broken links with `$ find ~/. -xtype l`

The error message is still there. What else can I do?

**Comment by KarlStraussberger** [comment]
Where does the error message show up. Syslog or gerbera.log.

Can you run gerbera with --debug command line option.

**Comment by efermi** [comment]
In the syslog. When running it with --debug option the related output is as follows:
```
2024-02-26 18:58:29.040  trace: [autoscan_inotify.cc:179] threadProc(): inotify event: 210 mask=0x8 name=.mpdascache
2024-02-26 18:58:29.040  error: [autoscan_inotify.cc:203] threadProc(): Failed to read /home/user/.mpdascache: No such file or directory
2024-02-26 18:58:29.040  trace: [autoscan_inotify.cc:210] threadProc(): autoscan not found in watches? (210, watchAs:true, adir:true, /home/user/.mpdascache)
```

**Comment by KarlStraussberger** [comment]
Can you give a bit more of the log context, so that I can anticipate the logical flow (call history) that leads to the error.

**Comment by KarlStraussberger** [comment]
It is highly recommended to rebuild it from scratch, because there are many new features that come with import. Be aware that 2.0 has some issues with importing playlists (already fixed in HEAD).

**Comment by efermi** [comment]
I've deleted the database and temporarily left an empty directory in the home dir as a single library location. The issue still persists, here is the full log:
[gerbera-output.log](https://github.com/gerbera/gerbera/files/14424084/gerbera-output.log)

**Comment by efermi** [comment]
I've setup a watch for the `~/.mpdascache` file like that:
```sh
inotifywait -m -e create,delete --include '\.mpdascache' /home/user |
while read path action file; do
    echo "The file '$file' $action in '$path' at $(date)"
done
```
and it is indeed being created and deleted multiple times per second indefinitely while the mpdas.service is running as can also be seen here https://github.com/hrkfdn/mpdas/blob/c81c480a6081af104c70c3574fb71319ff1521b7/cache.cpp#L5 IIUIC. While there is probably a better way to do it, is it possible to make gerbera ignore these events which happen outside of specified library locations?

**Comment by KarlStraussberger** [comment]
Now I understand the problem: we monitor all parent dirs of autoscan entries to see when they go any (e.g. unmount). This monitoring has to handle the parent dirs differently.

**Comment by KarlStraussberger** [comment]
Finally, I've found some time to test this in current head. We detect the file which is already gone when we try to analyse it further in your case. 
We can suppress the message if we're outside an autoscan dir.

**Comment by efermi** [comment]
Sounds good to me.
